[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/Paillat-dev/saferaise/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""

[git]
conventional_commits = false
commit_preprocessors = [
    { pattern = '\n.*', replace = "" },
]
commit_parsers = [
    { message = "^[Cc]hore", group = "Chores" },
    { message = "^[Ff]eat", group = "New Features" },
    { message = "^[Ff]ix", group = "Bug Fixes" },
    { message = "^[Ff]ix", group = "Bug Fixes" },
    { message = "^[Rr]efactor", group = "Refactor" },

    { message = "^:sparkles:", group = "New Features" },
    { message = "^:bug:|^:adhesive_bandage:", group = "Bug Fixes" },
    { message = "^:recycle:", group = "Refactor" },
    { message = "^:white_check_mark:|^:test_tube:", group = "Tests" },
    { message = "^:memo:|^:pencil2:|^:bulb:|^:speech_balloon:", group = "Documentation" },
    { message = "^:wrench:|^:label:|^:arrow_up:|^:arrow_down:|^:heavy_plus_sign:|^:heavy_minus_sign:|^:building_construction:", group = "Chores" },
    { message = "^:page_facing_up:|^:see_no_evil:", group = "Chores" },
    { message = "^:zap:", group = "Performance" },
    { message = "^:lock:", group = "Security" },
    { message = "^:lipstick:", group = "UI" },
    { message = "^:rotating_light:", group = "Chores" },
    { message = "^:green_heart:", group = "CI" },
    { message = "^:fire:|^:wastebasket:", group = "Removals" },
    { message = "^:rocket:", skip = true },
    { message = "^:tada:", skip = true },
]