[changelog]
body = """
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/Paillat-dev/saferaise/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""

[git]
conventional_commits = false
commit_preprocessors = [
    { pattern = '\n.*', replace = "" },
]
commit_parsers = [
    { message = "^:sparkles:|^[Ff]eat|^:rocket:|^:tada:", group = "Added" },
    { message = "^:bug:|^:adhesive_bandage:|^[Ff]ix|^:rotating_light:|^:green_heart:", group = "Fixed" },
    { message = "^:zap:|^:lipstick:|^:label:|^:page_facing_up:|^:see_no_evil:", group = "Changed" },
    { message = "^:fire:|^:coffin:", group = "Removed" },
    { message = "^:wastebasket:", group = "Deprecated" },
    { message = "^:lock:", group = "Security" },
    { message = "^:memo:|^:pencil2:|^:bulb:|^:speech_balloon:", group = "Documentation" },
    { message = "^:recycle:|^[Rr]efactor|^:wrench:|^:arrow_up:|^:arrow_down:|^:heavy_plus_sign:|^:heavy_minus_sign:|^:building_construction:|^:white_check_mark:|^:test_tube:|^[Cc]hore", group = "Chores" },
]