name: Release
on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  quality:
    uses: ./.github/workflows/quality.yaml
    permissions:
      contents: read

  publish:
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      id-token: write
      contents: write
    environment:
      name: pypi
      url: https://pypi.org/project/saferaise/

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: "Install uv"
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: "pyproject.toml"

      - name: "Install dependencies"
        run: uv sync
        env:
          UV_PYTHON_DOWNLOADS: "false"
          UV_FROZEN: "true"

      - name: "Build"
        run: uv build

      - name: "Publish"
        run: uv publish

      - name: "Generate Changelog"
        uses: orhun/git-cliff-action@v4
        id: cliff
        with:
          config: cliff.toml
          args: --latest --strip header

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          prerelease: ${{ contains(github.ref_name, '-') }}
          body: |
            ${{ steps.cliff.outputs.content }}
            ## Upgrade
            ```bash
            pip install -U saferaise
            ```
            
            ---
